### ISSUE TITLE
Playback stalls at 1.2 seconds with VVenC v1.10 during panning shot

### ISSUE THREAD

**Issue by jungleboynx** [fraunhoferhhi/vvenc#343]
If the video is panning or moving at the start then the decoder stalls briefly at 1.2 seconds.
I saw this same problem with v1.9.0 but cured it by increasing the refresh period to 2 or 4 seconds.
I tried the same trick with v1.10.0 but this didn't work so I switched back to v1.9.0 and no stall occurs with -rs 2 or -rs 4.
Encoding with VVenC v1.9.0 gives a brief stall at 0.6 sec with -rs 1.
Any video with motion at the start should show the problem.
I assume the v1.10.0 problem is caused by the change of the initial IDR frame to POC31.
You won't see the problem with static video at the start - you need video with movement at the start to see the problem.

I've built mpv with the latest VVdeC and ffmpeg 6.1.1
Interestingly the problem only occurs when playing the muxed mp4 file.
The problem doesn't occur when playing the raw vvc file. This might be a clue.
mpv doesn't show any error information in debug mode.
The PC used for playback is a 6C/12T processor.

Command line settings:
vvencapp -q 28 --preset fast -rs 1 -c yuv420 -t 12 --sdr sdr_709 -i video.y4m -o video.vvc
mp4box -add video.vvc video.mp4

Problem seen with -rs 1 with v1.9.0 and v1.10.0 in video.mp4 only but not video.vvc.
Changing to -rs 2 stops the stall problem with v1.9.0 but makes no difference with v1.10.0 

Here's the 3 second y4m video sample file which I had problems with (252MB):
https://www.dropbox.com/scl/fi/7wrhs24upj413pwk7i4jr/Test.Video.y4m?rlkey=cwgrkqdfptb0rkqn775qn6mj1&dl=0

**Comment by K-os** [comment]
Thanks for the report. I'll have a look into it.

**Comment by K-os** [comment]
The problem is neither a bug in VVenC nor in VVdeC, but in GPAC/MP4Box. When muxing the bitstream, MP4Box miscalculates the composition timestamps, which results in the player not showing the frames at the correct time.

Dumping the MP4 structure (`MP4Box -diso video.mp4`), and looking at the CTS offsets, we see the following:
```
> grep CompositionOffsetEntry video_info.xml`
<CompositionOffsetEntry CompositionOffset="7" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="5" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="10" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="5" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="2" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="0" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="1" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="3" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="1" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="2" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="6" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="3" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="1" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="2" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="4" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="2" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="3" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="7" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="4" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="2" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="3" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="5" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="3" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="4" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="28" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="19" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="10" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="5" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="2" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="0" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="1" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="3" SampleCount="1"/>
<CompositionOffsetEntry CompositionOffset="1" SampleCount="1"/>
...
```

This results in the following CTS calculations:
```
dts + offs = cts   
  0 +   7  =  7
  1 +   5  =  6
  2 +  10  = 12
  3 +   5  =  8
  4 +   2  =  6 ==> duplicate
  5 +   0  =  5
  6 +   1  =  7 ==> duplicate
  7 +   3  = 10
  8 +   1  =  9
  9 +   2  = 11
 10 +   6  = 16
 11 +   3  = 14
 12 +   1  = 13
 13 +   2  = 15
 14 +   4  = 18
 15 +   2  = 17
 16 +   3  = 19
 17 +   7  = 24
 18 +   4  = 22
 19 +   2  = 21
 20 +   3  = 23
 21 +   5  = 26
 22 +   3  = 25
 23 +   4  = 27
 24 +  28  = 52
 25 +  19  = 44
 26 +  10  = 36
 27 +   5  = 32
 28 +   2  = 30
 29 +   0  = 29
 30 +   1  = 31
 31 +   3  = 34
 32 +   1  = 33
...
```
The CTSs 6 & 7 are duplicated and CTSs 20 & 28 are missing. This results in the playback freezing, because the player does not know at which point in time to display those.

I have seen this bug in GPAC before and started work on a bugfix. I will make sure it doesn't break anything and then contribute it to GPAC upstream.

In the meantime, you can encode and mux the video using ffmpeg:
`ffmpeg -i ~/tmpfs/Test.Video.y4m -an -c:v vvc -qp 28 -period 1 -preset fast video.mp4`
More details here: https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#usage-1

**Comment by jungleboynx** [comment]
Yes, that's make sense.

I had a bodge solution - I shifted the --poc0idr option from the expert encoder to the simple encoder.
This allows the initial IDR to be shifted back to POC0 so it behaves like v1.9.0

--poc0idr 1 -rs 1 ... gives the stall problem with v1.10.0
--poc0idr 1 -rs 2 ... plays back ok with v1.10.0

**Comment by adamjw24** [comment]
Don't bodge stuff like that. Use `--additional POC0IDR=1` ;)

**Comment by jungleboynx** [comment]
Thank, I'll give it a go.

**Comment by K-os** [comment]
> Will you be reporting the bug to GPAC/mp4box ? They might listen to you.

Yes I will.

**Comment by K-os** [comment]
I haven't gotten around to submitting a proper bug report to the GPAC repo, yet. But you can try the bugfix from my fork of the GPAC repo: https://github.com/K-os/gpac branch `fix_idr_cts_probe_min_poc`

**Comment by jungleboynx** [comment]
Thanks, I give a try in the morning.
Will the initial IDR frame stay at a fixed POC31 or will it change depending on the refresh period value ?

**Comment by K-os** [comment]
FYI: The CTS bug should now be fixed in the master branch of in the upstream GPAC repository, so you don't need my patched version any more.

**Comment by birdie-github** [comment]
I've tried the latest MP4Box snapshot and the issue persists for me.

Both the source raw H.266 file and MP4 mux stall for 2 seconds before ffplay/mpv start playing them.

The clip was encoded using vvenc with no special options, just preset `slow`.

https://mega.nz/folder/rh9GQK7I#d1-4AZ4Wx59FahbgHieibw

**Comment by birdie-github** [comment]
@K-os please advise.

**Comment by jungleboynx** [comment]
I see a static image for the first 6.850 sec in the 29.mp4 file before movement occurs.
I muxed the y4m.266 into another mp4 using my modified mp4box and it shows the same thing - static picture for the first 6.850 sec.
The problem I had was a stall within the first GOP period caused by a bug in mp4box.
Both mp4 files have the same filesize but different MD5 hashes.
You're using mp4box GPAC2.3-DEV-revrelease.
I'm also using mp4box GPAC2.3-DEV-revrelease but it's the version built by K-os.

Your MD5 hash for 29.mp4 is DE5D22104092F40E8F68EBFC21E9FC8C
My MD5 hash for  y4m.mp4 is E6991C019BA7E3028B4DA6AB96CE8333

**Comment by K-os** [comment]
@birdie-github: I looked into the files you provided. There is nothing wrong with the MP4 muxing. There is just a still image the first ~15 seconds of your content.

**Comment by birdie-github** [comment]
@K-os 

I get a six (!) seconds stall here with 100% CPU use across all cores (8 physical, 16 SMT, Ryzen 5800X). That doesn't look "normal" at all.

Using mpv 0.35.1 + ffmpeg 6.0.1 + vvdec 2.2.0.

Could be an issue with ffmpeg + vvdec integration, of course which is not something you have power over.

**Comment by K-os** [comment]
Ok, I'll look into it again.

**Comment by birdie-github** [comment]
@K-os 

I've uploaded the source video into the same folder.

Encoding was done this way:

```
ffmpeg -i *webm -r 60 -f yuv4mpegpipe -hide_banner -loglevel error - | vvencapp --y4m -i - --preset slow -q 29 -o y4m.266
```

BTW, `vvenc` did **not** accept the source video framerate, so I had to use `-r 60` option for ffmpeg.

Maybe you could look into that as well.

**Comment by K-os** [comment]
Oh, sorry yes. It's not 16 seconds, but 6.8 seconds. I accidentally played the raw bitstream at 25 Hz. But the first 410 pictures are definitely identical, both in the 29.mp4 and in the y4m.266 files. I checked that by decoding both with vvdecapp directly and looking at the resulting YUVs.

Why that differs from the original webm file you provided is another question, but has nothing to do with VVdeC.

I guess that has something to do with your encoding. Can you please provide the exact command line and vvenc/ffmpeg versions you used to encode the file?

**Comment by birdie-github** [comment]
@K-os 

#360

**Comment by jungleboynx** [comment]
Yes birdie's source is 60fps but mpv plays the raw vvc at the default of 25fps. This is some recent change in mpv.
Once the vvc file is muxed into mp4 with the correct frame rate then the timing is correct.
I don't think the two things are related. My source had motion from the start but mysterious stalled for a short time whereas birdie's source (from game footage) is static from the start for a much longer period.
What's needed is birdie's y4m source file that was used for encoding the 266 file - just the first 10 seconds.

**Comment by lehmann-c** [comment]
> @K-os
> 
> I've uploaded the source video into the same folder.
> 
> Encoding was done this way:
> 
> ```
> ffmpeg -i *webm -r 60 -f yuv4mpegpipe -hide_banner -loglevel error - | vvencapp --y4m -i - --preset slow -q 29 -o y4m.266
> ```
> 
> BTW, `vvenc` did **not** accept the source video framerate, so I had to use `-r 60` option for ffmpeg.
> 
> Maybe you could look into that as well.

As ffmpeg in generating a strange frame rate for 59.,95Hz (19001/317) it cannot be processed as the vvencapp is possibly telling you:
`Parameter Check Error: Detected non-standard Frame Rate 19001/317 (59.94 Hz). Default TicksPerSecond (27000000) can not be used. possible TicksPerSecond: 6023317`
Just do as the app is telling you by setting the correct TicksPerSecond and it will work:
`ffmpeg -i *webm -f yuv4mpegpipe -hide_banner -loglevel error - | vvencapp --y4m -i - --preset slow -q 29 --tickspersec 6023317 -o y4m.266`
